import type { FC, PropsWithChildren } from "react";
import BaseLayout from "~/layouts/Base";
import "~/styles/globals.css";
import { Inter } from "next/font/google";

import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const RootLayout: FC<PropsWithChildren> = async ({ children }) => {
    return (
        <html lang="en">
            <body
                className={`bg-neutral-50 font-sans text-neutral-700 ${inter.variable}`}
                suppressHydrationWarning
            >
                <BaseLayout>{children}</BaseLayout>
            </body>
        </html>
    );
};

export default RootLayout;
