import type { FC, PropsWithChildren } from "react";
import BaseLayout from "~/layouts/Base";
import "~/styles/globals.css";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

const RootLayout: FC<PropsWithChildren> = async ({ children }) => {
    return (
        <html lang="en">
            <body
                className="bg-neutral-50 text-neutral-700"
                suppressHydrationWarning
            >
                <BaseLayout> {children}</BaseLayout>
            </body>
        </html>
    );
};

export default RootLayout;
